### ISSUE TITLE
Error: Waiting for form to provide assay

### ISSUE THREAD

**Issue by FilipeJesus** [pinin4fjords/shinyngs#1]
Hi, I have been having a issue where my assays are not being passed into the app. While on the server I receive the error "Waiting for form to provide assay", which never loads.
I am creating my exploratory summarizedexperiment from scratch using the code below.

`csvfile <- file.path("~/Documents/CHO", "colData.csv")
sampleTable <- read.csv(csvfile, row.names = 1)

myassays <- list()
myassays[[1]] <- dgel$counts
myassays[[2]] <- dgel2$counts
myassays[[3]] <- dgel3$counts
class(myassays[[1]])
head(myassays[[1]])

mycoldata <- data.frame(sampleTable)
class(mycoldata)
head(mycoldata)

myannotation <- DataFrame(fc$annotation)
class(myannotation)
head(myannotation)

myese <- ExploratorySummarizedExperiment(assays = SimpleList(myassays), colData = DataFrame(mycoldata), annotation <- myannotation, idfield = 'GeneID')

myesel <- ExploratorySummarizedExperimentList(eses = list(expression = myese), title = "My title", author = "My Authors", description = 'Look what I gone done')

app <- prepareApp("rnaseq", myesel)
shiny::shinyApp(app$ui, app$server)`

I am having to create a exploratory summarizedexperiment from scratch as i am using featurecounts to generate my count data.

**Comment by pinin4fjords** [comment]
Hi,

Try naming the assays list. The list of assay drop-downs is generated from those values, so if they're absent the script will never get one.

I've recently improved the loading from YAML files, which simplifies things greatly, I'll update the documentation soon- and it shouldn't matter where the assay matrices come from.

Jon

**Comment by FilipeJesus** [comment]
That worked! Thank you

**Comment by pinin4fjords** [comment]
Glad to help. Would love to hear feedback on the tool in future.
