### ISSUE TITLE
issue when creating contrast groups

### ISSUE THREAD

**Issue by FilipeJesus** [pinin4fjords/shinyngs#2]
Hi, I am having issues with telling the app which groups I want to contrast. At the moment i have it used this

`IL13NGvCAT.S <- c("cellines", "IL13NG", "CAT.S")
LOX.1vCAT.S <- c("cellines", "LOX.1", "CAT.S")
LOX.1vIL13NG <- c("cellines", "LOX.1", "IL13NG")
myesel@contrasts <- list(IL13NGvCAT.S, LOX.1vCAT.S, LOX.1vIL13NG)`

This gives me the error: subscript out of bounds

My colnames column called cell lines associates each sample to one of the 3 cell lines, LOX.1, CAT.S and IL13NG. I would like to compare each cell line to the other. I noticed in the neuron example that the contrasts are between the cells of a specific cell line vs all those not of that cell line. I have got that working on my data but those are not the comparisons I need.

**Comment by pinin4fjords** [comment]
Hi,

So, the tool just picks out groups of samples by referencing columns of the colData() in the current assay. Are you sure that e.g. 'Lox.1' and 'Cat.S' are values of the 'cellines' column in the colData() of your assay? 

e.g. first contrast of zhangneurons: 

`[1] "myelinating_oligodendrocytes" "0"                            "1" `

So to check:`\

```
> '0' %in% colData(zhangneurons$gene)[['myelinating_oligodendrocytes']]
[1] TRUE
```

```
> '1' %in% colData(zhangneurons$gene)[['myelinating_oligodendrocytes']]
[1] TRUE
```
Could you run a similar check to make sure those contrast values (LOX.1, CAT.S etc) are present as values in a 'cellines' column of your individual ExploratorySummarizedExperiments?

**Comment by pinin4fjords** [comment]
You could check the class of the 'cellines' variable in the colData(). If it's a factor rather than character that could be causing trouble.
