### ISSUE TITLE
App crashes after closing help messages

### ISSUE THREAD

**Issue by christianholland** [pinin4fjords/shinyngs#3]
After closing the help messages (using "x" or "close"-button) the app crashes. Tried in Chrome 64.0.3282.140 and Safari 11.0.2 (13604.4.7.1.3)

**Comment by pinin4fjords** [comment]
I'll look into it. Could you let me know your R version, and let me know if it's the example dataset you're using?

**Comment by christianholland** [comment]
My R version is 4.3.4 but not sure if this matters because i run your application with the example dataset on https://pinin4fjords.shinyapps.io/shinyngs_example/.

**Comment by pinin4fjords** [comment]
Ahh, well that's useful to know- thanks. Used to be fine, might be a change on their end

**Comment by christianholland** [comment]
I agree, because i seem to remember that this feature worked before

**Comment by pinin4fjords** [comment]
This is not obviously happening for me now when running locally, closing issue.
