### ISSUE TITLE
subscript out of bounds when using yaml to create object

### ISSUE THREAD

**Issue by sudeep71** [pinin4fjords/shinyngs#4]
Hi

using the yaml file as shown to create my object. The data loads up but when i want to visualize the volcano plots, i get to see the contrasts but the main page gives "subscript out of bounds". I use str() to parse out the object made but looks like it has colData groups as factor instead of character (as mentioned by previous user). I tried using ways to parse the object but cannot reach the colData object. 

Any help would be great !!!

Thanks!

**Comment by pinin4fjords** [comment]
Hi - could you save your object using saveRDS() and post it somewhere for me to download? Then I can test it myself. Bear with me though- don't have a lot of time spare ATM.
