### ISSUE TITLE
Problem with creating ESE, non-numeric matrix extent

### ISSUE THREAD

**Issue by wbarakat** [pinin4fjords/shinyngs#5]
Hello,

I am having issues with creating the ESE. I only have one assay in my list and I made sure the length of the IDs match for myassays and mycoldata but whenever I try and create the ESE object it gives me this error:

Error in matrix(NA, nrow = length(missing_rows), ncol = ncol(x)) : 
  non-numeric matrix extent

Thanks

**Comment by pinin4fjords** [comment]
Please provide the exact command you're trying to run, and any objects you're passing (you can serialize them with saveRDS()), and I'll do my best to help when I can. Do also bear in mind that I'm not currently maintaining this project, you may want to look at projects like iSEEE.

**Comment by wbarakat** [comment]
Thanks for the quick reply. I will take a look at iSEE. Here is the command. myassays is just a count table, ID is a dataframe with one column defining groups and the IDs that match my assays columns as rownames. 
myese <- ExploratorySummarizedExperiment(
  assays = SimpleList(
    myassays
  ),
  colData = mycoldata
)

**Comment by pinin4fjords** [comment]
Sorry, if you want me to help I'm actually going to need the objects you're using. The syntax you have looks roughly right according to the vignette, but I can't reproduce it without the objects you're using. You can serialize them and upload them here, and I'll take a look when I can.

**Comment by wbarakat** [comment]
Hey I figured it out, thank you for your time and help
