### ISSUE TITLE
Issue getting zhangneurons

### ISSUE THREAD

**Issue by drmarkreuter** [pinin4fjords/shinyngs#6]

**Comment by drmarkreuter** [comment]
> install_github('pinin4fjords/zhangneurons')
Downloading GitHub repo pinin4fjords/zhangneurons@master
pinin4fjords-zhangneurons-b0a41b0/inst/extdata/gene_sets/c5.bp.v5.2.symbols.mmusculus.gmt: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: running command 'tar.exe -zxf "C:\Users\ksxm410\AppData\Local\Temp\RtmpW00PVS\file484051fa31f3.tar.gz" -C "C:/Users/ksxm410/AppData/Local/Temp/RtmpW00PVS/remotes48404c677f4"' had status 1 
2: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\ksxm410\AppData\Local\Temp\RtmpW00PVS\file484051fa31f3.tar.gz" -C "C:/Users/ksxm410/AppData/Local/Temp/RtmpW00PVS/remotes48404c677f4"’ returned error code 1
3: running command 'tar.exe -ztf "C:\Users\ksxm410\AppData\Local\Temp\RtmpW00PVS\file484051fa31f3.tar.gz"' had status 1

**Comment by pinin4fjords** [comment]
Not sure what this was, the zhangneurons package is installing fine for me, and in CI, closing for now
